### ISSUE TITLE
Cannot use GraphQLSchema "[object GraphQLSchema]" from another module or realm.

### ISSUE THREAD

**Issue by emyann** [Camji55/nexus-plugin-jwt-auth#29]
Hello! 

I'm using the version `0.23.0-next.10` of nexus in a yarn workspace and after having installed the plugin I had the following error

```
       | error  Error: Cannot use GraphQLSchema "[object GraphQLSchema]" from another module or realm.
       |
       |        Ensure that there is only one instance of "graphql" in the node_modules
       |        directory. If different versions of "graphql" are the dependencies of other
       |        relied on modules, use "resolutions" to ensure only one version is installed.
       |
       |        https://yarnpkg.com/en/docs/selective-version-resolutions
       |
       |        Duplicate "graphql" modules cannot be used at the same time since different
       |        versions may have different capabilities and behavior. The data from one
       |        version used in the function from another could produce confusing and
       |        spurious results.
       |            at instanceOf (node_modules/nexus/node_modules/graphql/jsutils/instanceOf.js:28:13)
       |            at isSchema (node_modules/nexus/node_modules/graphql/type/schema.js:36:34)
       |            at assertSchema (node_modules/nexus/node_modules/graphql/type/schema.js:40:8)
       |            at validateSchema (node_modules/nexus/node_modules/graphql/type/validate.js:44:28)
       |            at assertValidSchema (node_modules/nexus/node_modules/graphql/type/validate.js:68:16)
       |            at Object.validate (node_modules/nexus/node_modules/graphql/validation/validate.js:54:35)
       |            at node_modules/nexus/src/runtime/server/handler-graphql.ts:45:30
       |            at process._tickCallback (internal/process/next_tick.js:68:7)
``` 
I think the issue might be due to the version of nexus (`0.21.0-next.5`) in the package.json. I tried to stick my version to `0.21.0-next.5` but was not able to make it work. I'm still not sure about the issue but would it make sense to have nexus as a peer dependency ?

**Comment by emyann** [comment]
Hmm never mind 😅 I had a version of graphql specified in one of my projects in the monorepo. Just removing it has fixed the issue, so I'm closing this issue!
